config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "wows#index"
  resources :wows do
    resources :locations, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :wow
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :wows
  has_many :locations
end

app/models/wow.rb
class Wow < ApplicationRecord
 validates :comment, presence: true
 validates :picture, presence: true
 has_many :locations
 mount_uploader :picture, PictureUploader
 belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} :(", status: status
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @wow = Wow.find_by_id(params[:wow_id])
    return render_not_found if @wow.blank?

    @wow.locations.create(location_params.merge(user: current_user))
    redirect_to root_path
  end

  private

  def location_params
    params.require(:location).permit(:comment)
  end


end

app/controllers/wows_controller.rb
class WowsController < ApplicationController
   before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def new
    @wow = Wow.new
  end

  def destroy
    @wow = Wow.find_by_id(params[:id])
    return render_not_found if @wow.blank?
    return render_not_found(:forbidden) if @wow.user != current_user
    @wow.destroy
    redirect_to root_path
  end

  def index
    @wows = Wow.all
  end

  def show
    @wow = Wow.find_by_id(params[:id])
    return render_not_found if @wow.blank?
  end

  def edit
    @wow = Wow.find_by_id(params[:id])
    return render_not_found if @wow.blank?
    return render_not_found(:forbidden) if @wow.user != current_user
  end

  def update
    @wow = Wow.find_by_id(params[:id])
    return render_not_found if @wow.blank?
    return render_not_found(:forbidden) if @wow.user != current_user
    @wow.update_attributes(wow_params)
    if @wow.valid?
    redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def create
    @wow = current_user.wows.create(wow_params)
    if @wow.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def wow_params
    params.require(:wow).permit(:comment, :picture)
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/wows_helper.rb
module WowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tuwow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,100,300,600,700' rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div class="top-nav">
    <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
      <div class="brand float-left">
        Tu Sais Le Wow!
      </div>
      <div class="add float-right">
        <% if current_user %>
          You're signed in as <%= current_user.email %>.
          <%= link_to "New Wow!", new_wow_path %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %>
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </div>
    <br class="clear-fix" />
  </div>

    <%= yield %>
  </body>
</html>

app/views/wows/edit.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">
  <h2>Edit Wow</h2>

  <%= simple_form_for @wow do |f| %>
    <%= f.input :comment %>
    <%= f.input :picture %>
    <%= f.submit 'Update', class: 'my-btn' %>
  <% end %>

</div>

app/views/wows/index.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
  <% @wows.each do |wow| %>
  <div class="card">
    <div class="handle"><%= wow.user.email %></div>
    <%= image_tag wow.picture.to_s, class: 'img-fluid' %>
    <p>
    <%= wow.comment %>
    </p>

    <div class="wow-actions float-right">
      <% if current_user && current_user == wow.user %>
        <%= link_to 'Edit', edit_wow_path(wow) %>
        <%= link_to 'Destroy', wow_path(wow), method: :delete, data: {confirm: 'Delete will occur next!'} %>
      <% end %>
    </div>
    <br class="clear-fix" />
    <div class="locations">
      <h3>Location</h3>
      <% wow.locations.each do |location| %>
          <div class="location">
            <span class="location_handle">
              <%= location.comment %>
            </span>
          </div>
        <% end %>

      <h4>Add Your Wow Address!</h4>
      <%= simple_form_for Location.new, url: wow_locations_path(wow) do |f| %>
        <%= f.input :comment %>
        <%= f.submit 'Add Wow Address.', class: 'my-btn' %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/wows/new.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">

  <h1>New Wow</h1>

  <%= simple_form_for @wow do |f| %>
    <%= f.input :comment %>
    <%= f.input :picture %>
    <%= f.submit "Submit!", class: 'my-btn' %>
  <% end %>

</div>

app/views/wows/show.html.erb
<%= @wow.inspect %>